name: Create Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, amd64, amd64_arm64]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Prepare environment vars
        shell: pwsh
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          $target_arch = "${{ matrix.arch }}" -replace ".*_"
          "RELEASE_TAG=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CONVEY_VERSION=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "TARGET_ARCH=$target_arch" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RELEASE_ASSET_NAME=convey-$tag-$target_arch.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Compile convey
        run: nmake VERSION=${{ env.CONVEY_VERSION }}
      - name: Package release build
        run: 7z a ${{ env.RELEASE_ASSET_NAME }} convey.exe convey.pdb LICENSE README.md
      - name: Upload release build
        shell: pwsh
        run: gh release upload "${{ env.RELEASE_TAG }}" "${{ env.RELEASE_ASSET_NAME }}" --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

